### ISSUE TITLE
How to call  api when server is behind a proxy 

### ISSUE THREAD

**Issue by mgrivera** [cloudcmd/dropbox#1]
Hi all, 

When my app executes a command, for example: 

` readDir(token, folderPath, { type, sort, order }) `

and the server is behind a proxy, the execution receives an error: 

 TypeError: Cannot read property 'error_summary' of undefined

So, I'm wondering if there is a way to specify proxy settings (ie: http://user:pwd@proxy:port) when making the call??? 

Many thanks ...

**Comment by coderaiser** [comment]
Hi, are you talking about `dropbox` server behind proxy? Could you please tell me what purpose of it?

**Comment by mgrivera** [comment]
Well, I installed my app in a server that is in a network that is behind a proxy. 

For example, to clone my app from github I had to set the proxy credentials in git config file. 
To download packages from npm I had to initialize some variables to set proxy credentials. 

My app uses DropBox to keep some files and use your library to read and write files from/to DropBox. This app is failing in this server but not in other clients. I think it is because of the proxy. I think I have to set the proxy credentials somewhere so that your library can read/write from/to DB. 

If this is correct, so how do I set proxy settings somewhere? 
But maybe it is not even possible ...

**Comment by coderaiser** [comment]
Looks like this is related to https://github.com/dropbox/dropbox-sdk-js/issues/150. I think it is possible to proxy requests to drobox server, but it should be implemented in `drobox sdk` first.

Anyways pull requests are wellcome, I think it's useful feature :).

**Comment by coderaiser** [comment]
#
Closed due to a long time of inactivity 🏝
